
#ifndef __STATUS_H__
#define __STATUS_H__

typedef enum {
	USERNOTFOUND = 101,
	USERISBLOCKED = 102,
	BLOCKEDUSER = 103,
	PASSWORDINVALID = 104,
	FILENOTFOUND = 108,
	LOGINSUCCESS = 201,
	USERISONLINE = 105,
	ACCOUNTISEXIST = 106,
	REGISTERSUCCESS = 202,
	LOGOUTSUCCESS = 203,
	USERNAMEORPASSWORDINVALID = 107,
	COMMANDINVALID = 301,
	SERVERERROR = 500
} Status_Code;

void message_Code(Status_Code code1, char *msg1);
#endif